name: Sync Marketplaces

on:
  # Trigger on repository dispatch from child marketplaces
  repository_dispatch:
    types: [marketplace-updated]

  # Weekly sync to catch any missed updates
  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 2 AM UTC

  # Manual trigger for testing
  workflow_dispatch:
    inputs:
      verbose:
        description: 'Enable verbose logging'
        required: false
        default: 'false'

jobs:
  sync-marketplaces:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync marketplaces
        uses: ralphbean/claude-marketplace-sync@main
        with:
          config-path: '.sync-config.json'
          verbose: ${{ github.event.inputs.verbose || 'false' }}

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .claude-plugin/marketplace.json
          if git diff --staged --quiet; then
            echo "ℹ️  No changes to commit"
          else
            TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
            git commit -m "chore: sync marketplaces - $TIMESTAMP

            Automatically aggregated plugins from child marketplaces.
            Triggered by: ${{ github.event_name }}

            See .sync-config.json for source configuration."
            git push
            echo "✓ Changes committed and pushed"
          fi
