# GitLab CI/CD template for syncing Claude Code marketplaces
#
# This is a reusable template that can be included in your .gitlab-ci.yml file.
#
# USAGE:
#
# Basic usage (include and extend):
#   include:
#     - remote: 'https://raw.githubusercontent.com/ralphbean/claude-marketplace-sync/main/gitlab/gitlab-ci.yml'
#
#   sync-marketplaces:
#     extends: .sync-marketplaces-template
#     only:
#       - main
#
# Advanced usage (with customizations):
#   include:
#     - remote: 'https://raw.githubusercontent.com/ralphbean/claude-marketplace-sync/main/gitlab/gitlab-ci.yml'
#
#   sync-marketplaces:
#     extends: .sync-marketplaces-template
#     variables:
#       SYNC_CONFIG: ".my-custom-config.json"
#       OUTPUT_FILE: ".claude-plugin/my-marketplace.json"
#       VERBOSE: "true"
#     before_script:
#       - !reference [.sync-marketplaces-template, before_script]
#       - echo "Running custom setup commands"
#     only:
#       - main
#       - develop
#
# For local development/testing, use a local path:
#   include:
#     - local: 'gitlab/gitlab-ci.yml'

# Hidden template job (prefix with . to make it abstract)
# Users should extend this in their own .gitlab-ci.yml
.sync-marketplaces-template:
  image: registry.access.redhat.com/ubi10/python-312-minimal:latest
  stage: deploy

  # Default variables - can be overridden by extending jobs
  variables:
    SYNC_CONFIG: ".sync-config.json"
    OUTPUT_FILE: ".claude-plugin/marketplace.json"
    GIT_DEPTH: 0
    VERBOSE: "false"

  # Default rules - can be overridden by extending jobs
  # These provide sensible defaults but let users control via 'only:', 'except:', etc.
  rules:
    # Run on schedule (configure in GitLab CI/CD > Schedules)
    - if: $CI_PIPELINE_SOURCE == "schedule"
    # Run on manual trigger
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
    # Run on API trigger (repository_dispatch equivalent)
    - if: $CI_PIPELINE_SOURCE == "trigger"

  before_script:
    # Install dependencies
    - apt-get update && apt-get install -y git
    # Configure git for commits
    - git config --global user.name "GitLab CI/CD Bot"
    - git config --global user.email "cicd@gitlab.com"

  script:
    - echo "=== Syncing Claude Code Marketplaces ==="

    # Run the sync script
    - |
      if [ "$VERBOSE" == "true" ]; then
        python3 sync-marketplaces.py --config $SYNC_CONFIG --output $OUTPUT_FILE --verbose
      else
        python3 sync-marketplaces.py --config $SYNC_CONFIG --output $OUTPUT_FILE
      fi

    # Check for changes
    - |
      if git diff --quiet $OUTPUT_FILE; then
        echo "ℹ️  No changes detected"
        exit 0
      fi

    # Commit and push changes
    - git add $OUTPUT_FILE
    - |
      TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
      git commit -m "chore: sync marketplaces - $TIMESTAMP

      Automatically aggregated plugins from child marketplaces.
      Triggered by: $CI_PIPELINE_SOURCE

      See .sync-config.json for source configuration."

    # Push using CI/CD token
    - |
      git remote set-url origin "https://oauth2:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
      git push origin HEAD:${CI_COMMIT_REF_NAME}

    - echo "✓ Marketplace updated and pushed to $CI_COMMIT_REF_NAME"

  artifacts:
    paths:
      - .claude-plugin/marketplace.json
    expire_in: 30 days

  cache:
    paths:
      - .cache/pip
